"""Vietnamese financial news sentiment: PhoBERT encoder + custom transformer."""

from .data import (
    DatasetLoadConfig,
    SentimentDatasetBundle,
    deterministic_stratified_split,
    load_sentiment_dataset,
    save_dataset_manifest,
)
from .preprocessing import (
    PreprocessingConfig,
    VnCoreNLPSegmenter,
    apply_preprocessing,
    build_preprocessing_report,
    sample_preprocessing_examples,
)
from .modeling import (
    CustomTransformerSentimentModel,
    PhoBERTSentimentModel,
    SentimentQueryAttentionHead,
    expected_value_from_probabilities,
)
from .evaluation import (
    build_prediction_frame,
    compute_title_level_metrics,
    plot_confusion_matrix,
    plot_expected_value_scatter,
    plot_length_comparison,
    plot_metric_comparison,
    plot_preprocessing_examples_table,
    plot_preprocessing_label_distribution,
    plot_residual_histogram,
    plot_score_distribution_by_class,
    plot_training_curves,
)
from .handoff import (
    DEFAULT_SENTIMENT_OUTPUT_ROOT,
    PHASE3_HANDOFF_FILENAME,
    build_phobert_handoff,
    resolve_phobert_handoff,
    save_phobert_handoff,
)
from .inference import (
    PhoBERTInferenceBundle,
    PhoBERTInferencer,
    aggregate_title_sentiment_scores,
    flatten_sentiment_scores,
    load_phobert_inference_bundle,
)
from .training import (
    EncodedTextDataset,
    SimpleVocabulary,
    TrainingArtifacts,
    TrainingConfig,
    build_custom_text_datasets,
    build_dataloaders,
    build_phobert_text_datasets,
    evaluate_sentiment_model,
    make_class_weights,
    train_sentiment_model,
)

__all__ = [
    "DatasetLoadConfig",
    "SentimentDatasetBundle",
    "PreprocessingConfig",
    "CustomTransformerSentimentModel",
    "PhoBERTSentimentModel",
    "SentimentQueryAttentionHead",
    "EncodedTextDataset",
    "VnCoreNLPSegmenter",
    "apply_preprocessing",
    "build_custom_text_datasets",
    "build_dataloaders",
    "build_phobert_text_datasets",
    "build_prediction_frame",
    "build_preprocessing_report",
    "compute_title_level_metrics",
    "deterministic_stratified_split",
    "evaluate_sentiment_model",
    "expected_value_from_probabilities",
    "DEFAULT_SENTIMENT_OUTPUT_ROOT",
    "PHASE3_HANDOFF_FILENAME",
    "load_sentiment_dataset",
    "load_phobert_inference_bundle",
    "make_class_weights",
    "PhoBERTInferenceBundle",
    "PhoBERTInferencer",
    "plot_confusion_matrix",
    "plot_expected_value_scatter",
    "plot_length_comparison",
    "plot_metric_comparison",
    "plot_preprocessing_examples_table",
    "plot_preprocessing_label_distribution",
    "plot_residual_histogram",
    "plot_score_distribution_by_class",
    "plot_training_curves",
    "build_phobert_handoff",
    "resolve_phobert_handoff",
    "sample_preprocessing_examples",
    "save_dataset_manifest",
    "save_phobert_handoff",
    "SimpleVocabulary",
    "aggregate_title_sentiment_scores",
    "flatten_sentiment_scores",
    "TrainingArtifacts",
    "TrainingConfig",
    "train_sentiment_model",
]